export const GET_ALL_PRODUCT_SAGA = 'GET_ALL_PRODUCT_SAGA';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const ADD_PRODUCT_SAGA = 'ADD_PRODUCT_SAGA';
export const DELETE_PRODUCT_SAGA = 'DELETE_PRODUCT_SAGA';
export const UPDATE_PRODUCT_SAGA = 'UPDATE_PRODUCT_SAGA'