export const GET_PRODUCT_CATEGORY_FORM = 'GET_PRODUCT_CATEGORY_FORM';
export const GET_EDIT_PRODUCT_CATEGORY_FORM = 'GET_EDIT_PRODUCT_CATEGORY_FORM';
export const SET_EDIT_PRODUCT_CATEGORY_FORM = 'SET_EDIT_PRODUCT_CATEGORY_FORM';
export const SET_SUBMIT_CREATE_PRODUCT_CATEGORY = 'SET_SUBMIT_CREATE_PRODUCT_CATEGORY'
export const SET_SUBMIT_EDIT_PRODUCT_CATEGORY = 'SET_SUBMIT_EDIT_PRODUCT_CATEGORY'
export const GET_ALL_PRODUCT_CATEGORY = 'GET_ALL_PRODUCT_CATEGORY'

export const ADD_PRODUCT_CATEGORY_SAGA = 'ADD_PRODUCT_CATEGORY_SAGA';
export const GET_ALL_PRODUCT_CATEGORY_SAGA = 'GET_ALL_PRODUCT_CATEGORY_SAGA'
export const DELETE_PRODUCT_CATEGORY_SAGA = 'DELETE_PRODUCT_CATEGORY_SAGA'
export const UPDATE_PRODUCT_CATEGORY_SAGA = 'UPDATE_PRODUCT_CATEGORY_SAGA'