export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const GET_PRODUCT_FORM = 'GET_PRODUCT_FORM';
export const SET_SUBMIT_PRODUCT_FORM = 'SET_SUBMIT_PRODUCT_FORM';

export const GET_POST_CATEGORY_FORM = 'GET_POST_CATEGORY_FORM';
export const SET_SUBMIT_POST_CATEGORY_FORM = 'SET_SUBMIT_POST_CATEGORY_FORM';

export const GET_POST_FORM = 'GET_POST_FORM';
export const SET_SUBMIT_POST_FORM = 'SET_SUBMIT_POST_FORM';

export const GET_CHANGE_PASSWORD_FORM = 'GET_CHANGE_PASSWORD_FORM';
export const SET_SUBMIT_CHANGE_PASSWORD_FORM = 'SET_SUBMIT_CHANGE_PASSWORD_FORM';