export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const GET_PRODUCT_FORM = 'GET_PRODUCT_FORM';
export const SET_SUBMIT_PRODUCT_FORM = 'SET_SUBMIT_PRODUCT_FORM';